FROM python:3.12-slim 
WORKDIR /backend/app 
ENV PYTHONBUFFERD = 1

# Install dependencies

RUN apt-get update && apt-get install -y build-essential gcc && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy project codes
COPY . .

EXPOSE 8000

# Run the backend (uvicorn with reload for dev)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]