services:

  backend: 
    build:
      context: ./
      dockerfile: docker/DockerFile
    container_name: rtpoll-backend
    privileged: true
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    command: 
      uvicorn main:app --host 0.0.0.0 --port 8000 
    volumes:
      - ./backend/data:/app/data

  redis:
    container_name: rtpoll-redis 
    image: redis:7 
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq: 
    container_name: rtpoll-rmq 
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  celery-worker:
    build:
      context: ./
      dockerfile: docker/DockerFile
    container_name: rtpoll-celery-worker
    environment:
    - PYTHONPATH=/app
    command: celery -A app.setup.worker:celery_app worker -l info
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend/data:/app/data

  celery-beat:
    build:
      context: ./
      dockerfile: docker/DockerFile
    container_name: rtpoll-celery-beat
    environment:
    - PYTHONPATH=/app
    command: celery -A app.setup.worker:celery_app beat -l info
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend/data:/app/data

volumes:
  redis_data:
  nginx_certs:

