"""baseline schema

Revision ID: 2f2131247918
Revises: 
Create Date: 2026-06-29 00:19:38.621444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f2131247918'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poll_options', 'id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=18),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('poll_options_id_seq'::regclass)"))
    op.alter_column('poll_options', 'poll_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=18),
               existing_nullable=False)
    op.create_index(op.f('ix_poll_options_id'), 'poll_options', ['id'], unique=True)
    op.alter_column('polls', 'id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=18),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('polls_id_seq'::regclass)"))
    op.create_index(op.f('ix_polls_id'), 'polls', ['id'], unique=True)
    op.alter_column('polls_history_record', 'poll_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=18),
               existing_nullable=False)
    op.alter_column('polls_history_record', 'snapshot_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_constraint(op.f('uix_poll_timestamp'), 'polls_history_record', type_='unique')
    op.create_index('ix_poll_history_poll_date', 'polls_history_record', ['poll_id', 'snapshot_date'], unique=False)
    op.create_unique_constraint('uix_poll_snapshot_date', 'polls_history_record', ['poll_id', 'snapshot_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_poll_snapshot_date', 'polls_history_record', type_='unique')
    op.drop_index('ix_poll_history_poll_date', table_name='polls_history_record')
    op.create_unique_constraint(op.f('uix_poll_timestamp'), 'polls_history_record', ['poll_id', 'snapshot_date'], postgresql_nulls_not_distinct=False)
    op.alter_column('polls_history_record', 'snapshot_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('polls_history_record', 'poll_id',
               existing_type=sa.String(length=18),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_index(op.f('ix_polls_id'), table_name='polls')
    op.alter_column('polls', 'id',
               existing_type=sa.String(length=18),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('polls_id_seq'::regclass)"))
    op.drop_index(op.f('ix_poll_options_id'), table_name='poll_options')
    op.alter_column('poll_options', 'poll_id',
               existing_type=sa.String(length=18),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('poll_options', 'id',
               existing_type=sa.String(length=18),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('poll_options_id_seq'::regclass)"))
    # ### end Alembic commands ###
